### ISSUE TITLE
getLaidBinderByViewHolder throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by drakeet** [drakeet/MultiType#102]
I am sorry! There are still bugs when calling `getLaidBinderByViewHolder()` by `onViewDetachedFromWindow(holder)`.

```java
java.lang.IndexOutOfBoundsException: Index: 7, Size: 0
  at java.util.ArrayList.get(ArrayList.java:411)
  at me.drakeet.multitype.MultiTypeAdapter.getLaidBinderByViewHolder(MultiTypeAdapter.java:209)
  at me.drakeet.multitype.MultiTypeAdapter.onViewDetachedFromWindow(MultiTypeAdapter.java:202)
```

So, I have reverted the README to v2.4.3 and **DO NOT use v2.5.0-beta and v2.5.0-beta2** until the bug being fixed.

**Comment by drakeet** [comment]
https://github.com/drakeet/MultiType/commit/9061d247a4399a665d71ae73c4c52f1418a99e28
