### ISSUE TITLE
Crash if app reactive from background

### ISSUE THREAD

**Issue by specneeo** [drakeet/MultiType#14]
when press back key, and then restart app, it will crash.

Process: me.drakeet.multitype.sample, PID: 25781
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{me.drakeet.multitype.sample/me.drakeet.multitype.sample.page.MainActivity}: java.lang.IllegalArgumentException: You have registered the TextItemContent type. It should not be added again.
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2422)
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:159)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5313)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1116)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)
                                                                              Caused by: java.lang.IllegalArgumentException: You have registered the TextItemContent type. It should not be added again.
                                                                                 at me.drakeet.multitype.ItemTypePool.register(ItemTypePool.java:38)
                                                                                 at me.drakeet.multitype.sample.page.MainActivity.onCreate(MainActivity.java:65)
                                                                                 at android.app.Activity.performCreate(Activity.java:6036)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2422) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:159) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5313) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1116) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)

**Comment by drakeet** [comment]
It has been fixed, thank you for your help! By the way, the v1.2 has been released, [https://github.com/drakeet/MultiType/releases](https://github.com/drakeet/MultiType/releases), it is really gratifying! Good night : )

**Comment by specneeo** [comment]
感谢大神
在Readme文件中，你提到设计为静态或者全局类型，并说到一个应用不会有超级大量的类型定义。但是如果是对于淘宝这样的客户端，我觉得内部的类型定义会非常多，而且不同模块由不同的开发人员来维护，对于这种客户端，几百几千种类型都是很常见的，如果都把类型定义在Application中进行注册，（1）是否有利于方便的维护？，（2）类似淘宝这样的客户端，该如何处理？

**Comment by drakeet** [comment]
@simidaxu 我还是觉得不会太多，或许对于超级巨量的类型，可能需要支持局部类型池，不过我觉得暂时可以不必考虑，毕竟大部分应用远远说不上巨量。至于你说的统一在 `Application` 里注册担心堆积太多，可以仿造我的 `TimeMachine`，它在使用 `MultiType` 的时候，是在另外一个类中注册类型，所以如果类型太多，可以专门开一个类，通过静态方法和在 `Application` 静态调用来分解代码。如：

``` java
public class TypeRegister {

    public static void init() {
        /* register your types */
        ...
    }
}
```

然后在 `Application` 中调用这个方法来初始化。

**Comment by drakeet** [comment]
@simidaxu 或许我可以考虑下以比较好的方式支持局部类型池，似乎很多人在意这个事情...

**Comment by drakeet** [comment]
@simidaxu 对于全局类型池，我做的性能测试：https://github.com/drakeet/MultiType/issues/15 

结论就是，性能极好。
