### ISSUE TITLE
Weibo 例子中 withLinker 的疑问

### ISSUE THREAD

**Issue by LoveqLRC** [drakeet/MultiType#143]
版本号：`3.0.1`
源代码是这样
```
  adapter.register(Weibo.class).to(
            new SimpleTextViewBinder(),
            new SimpleImageViewBinder()
        ).withLinker(new Linker<Weibo>() {
            @Override
            public int index(@NonNull Weibo weibo) {
                if (weibo.content instanceof SimpleText) {
                    return 0;
                } else if (weibo.content instanceof SimpleImage) {
                    return 1;
                }
                return 0;
            }
        });
```
我把他改成这样(返回值调换了)
```
      if (weibo.content instanceof SimpleText) {
                    return 1;
                } else if (weibo.content instanceof SimpleImage) {
                    return 0;
                }
```
会报错
```
java.lang.ClassCastException: me.drakeet.multitype.sample.weibo.content.SimpleText cannot be cast to me.drakeet.multitype.sample.weibo.content.SimpleImage
                                                                                 at me.drakeet.multitype.sample.weibo.content.SimpleImageViewBinder.onBindContentViewHolder(SimpleImageViewBinder.java:32)
                                                                                 at me.drakeet.multitype.sample.weibo.WeiboFrameBinder.onBindViewHolder(WeiboFrameBinder.java:62)
                                                                                 at me.drakeet.multitype.sample.weibo.WeiboFrameBinder.onBindViewHolder(WeiboFrameBinder.java:36)
                                                                                 at me.drakeet.multitype.ItemViewBinder.onBindViewHolder(ItemViewBinder.java:83)
                                                                                 at me.drakeet.multitype.MultiTypeAdapter.onBindViewHolder(MultiTypeAdapter.java:233)
```
同样的在项目中，Items中添加item，如果withLinker返回的值(像上面那样0，1互换)不同，RecyclerView显示顺序并没有按照Items里面数据的顺序显示。

**Comment by drakeet** [comment]
这个错误提示很明显，`SimpleText` 无法转为 `SimpleImage`，说明你将 `SimpleText` 映射到一个 `SimpleImageViewBinder` 上了，当然会报错。
`withLinker#index` 方法的返回值是指你放入 `to(...)` 方法中的可变参数 index，你不能将一个 `SimpleText` 对象投向一个 `SimpleImageViewBinder`.

**Comment by drakeet** [comment]
你对调 `index`，那么 `to` 中的内容也应该对调。

**Comment by LoveqLRC** [comment]
Thank you very much for your answer

**Comment by drakeet** [comment]
You are welcome. :)
You could try this:
```java
adapter.register(Weibo.class).to(
    new SimpleImageViewBinder(),
    new SimpleTextViewBinder()
).withLinker(new Linker<Weibo>() {
    @Override
    public int index(@NonNull Weibo weibo) {
        if (weibo.content instanceof SimpleText) {
            return 1;
        } else if (weibo.content instanceof SimpleImage) {
            return 0;
        }
        return 1;
    }
});
```

**Comment by drakeet** [comment]
And If you do not want to use `withLinker#index`, you can also try `withClassLinker`. It may be more intuitive.

**Comment by LoveqLRC** [comment]
okay thanks for fast response
