### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by duckmoon** [drakeet/MultiType#222]
###### Info:

 - MultiType version: 

###### Description: 

![image](https://user-images.githubusercontent.com/5018105/42359707-385f6324-8116-11e8-92e4-27bfa80a5b6b.png)

java.lang.IndexOutOfBoundsException: Index: 10000, Size: 2
        at java.util.ArrayList.get(ArrayList.java:437)
        at me.drakeet.multitype.MultiTypePool.getItemViewBinder(MultiTypePool.java:143)
        at me.drakeet.multitype.MultiTypeAdapter.getRawBinderByViewHolder(MultiTypeAdapter.java:334)
        at me.drakeet.multitype.MultiTypeAdapter.onViewAttachedToWindow(MultiTypeAdapter.java:315)
        at com.jcodecraeer.xrecyclerview.XRecyclerView$WrapAdapter.onViewAttachedToWindow(XRecyclerView.java:655)
        at android.support.v7.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:6835)
        at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:715)
        at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
        at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7877)
        at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7835)
        at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7823)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1565)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
###### What did I do: 
I have tried to use normal RecyclerView.Adapter, the RecyclerView works fine, but use MultiType,  throws the exception. Hope for help, thanks!

**Comment by drakeet** [comment]
Could you please show the code about this:  
com.jcodecraeer.xrecyclerview.XRecyclerView$WrapAdapter.onViewAttachedToWindow(XRecyclerView.java:655)

**Comment by drakeet** [comment]
It seems that you pass a ViewHolder with a view type value `2000` to `onViewAttachedToWindow(MultiTypeAdapter.java:315)`, you changed the full logic and it's out of MultiType control.

**Comment by drakeet** [comment]
I am closing this issue as we don't have enough actionable information.
