### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by Skqing** [drakeet/MultiType#231]
```
    @NonNull @Override
    public ItemViewBinder<?, ?> getItemViewBinder(int index) {
        return binders.get(index);
    }
这里index是10000 为什么
```

```
2018-08-08 19:35:33.417 32127-32127/com.xxx.xxt E/CrashHandler: In thread: Thread[main,5,main]
    UncaughtException detected: java.lang.IndexOutOfBoundsException: Index: 10000, Size: 1
        at java.util.ArrayList.get(ArrayList.java:411)
        at me.drakeet.multitype.MultiTypePool.getItemViewBinder(MultiTypePool.java:133)
        at me.drakeet.multitype.MultiTypeAdapter.getRawBinderByViewHolder(MultiTypeAdapter.java:321)
        at me.drakeet.multitype.MultiTypeAdapter.onViewAttachedToWindow(MultiTypeAdapter.java:301)
        at com.jcodecraeer.xrecyclerview.XRecyclerView$WrapAdapter.onViewAttachedToWindow(XRecyclerView.java:655)
        at android.support.v7.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:7161)
        at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:782)
        at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
        at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8222)
        at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8180)
        at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8168)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1573)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1191)
        at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:876)
        at android.support.design.widget.ViewOffsetBehavior.layoutChild(ViewOffsetBehavior.java:63)
        at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:136)
        at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:894)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    	at android.widget.FrameLayout.onLayout(FrameLayout.jav

```

**Comment by drakeet** [comment]
你使用的 XRecyclerView#WrapAdapter 包裹并破坏了 MultiType 的程序行为，我不知道它做了什么，如果你无法解决，请不要和它一起使用。
