### ISSUE TITLE
我遇到一个问题

### ISSUE THREAD

**Issue by SnowWitch** [drakeet/MultiType#38]
FATAL EXCEPTION: main
                                                              Process: com.yunuo.ww, PID: 20664
                                                              java.lang.IndexOutOfBoundsException: Invalid index 4, size is 0
                                                                  at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                  at java.util.ArrayList.get(ArrayList.java:308)
                                                                  at com.yunuo.im.ui.activity.GroupProfileActivity$2.getSpanSize(GroupProfileActivity.java:120)
                                                                  at android.support.v7.widget.GridLayoutManager.getSpanSize(GridLayoutManager.java:475)
                                                                  at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:518)
                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                  at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2906)
                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                                                                  at android.view.View.layout(View.java:15748)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                  at android.view.View.layout(View.java:15748)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                  at android.view.View.layout(View.java:15748)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                  at android.view.View.layout(View.java:15748)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                  at android.view.View.layout(View.java:15748)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                  at android.view.View.layout(View.java:15748)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                  at android.view.View.layout(View.java:15748)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                  at android.view.View.layout(View.java:15748)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                                  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2124)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1876)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1080)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5877)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5475)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:948)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:743)。
而我的报错地方代码如下：
   layoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                Item item = items.get(position);
                return (items.get(position) instanceof SendMessage
                        || items.get(position) instanceof Spilt
                        || items.get(position) instanceof GroupMessage
                        || items.get(position) instanceof GroupTitle
                        || items.get(position) instanceof GroupMute) ? SPAN_COUNT : 1;
            }
        });
其中SPAN是4;但是出现数组越界，我下面布局有些是重复利用的，这种现象怎么解决？？

**Comment by drakeet** [comment]
这个问题应该是你的数据和 RV 不同步造成的，检查一下是否使用了不同 items 对象，是不是搞错了把数据填充到另一个 items 对象中了。

**Comment by SnowWitch** [comment]
谢谢，我找到错误了，我有个分割线的view，我以为没有数据，可以直接复用，没有重新new一个，而是在下面的地方直接添加上面那个，应该是这个原因导致的。

**Comment by SnowWitch** [comment]
我还想问一下，我上面是网格，但是网格增添或者删除，需要刷新显示，但是直接适配器刷新不起作用，我想问一下怎么才能单独刷新这个网格部分的items。

**Comment by SnowWitch** [comment]
添加网格的代码：  for (int i = 0; i < sortedUsers.size(); i++) {
            items.add(new GroupHead(chat_id, sortedUsers.get(i)));
        }

**Comment by drakeet** [comment]
只要数据源修改了后，直接调用 `Adapter.notifyDataSetChanged()` 或 `notifyItemChanged` 即可。

至于你说的没有重新 new 一个分割线 item，实际上 Items 是继承自 ArrayList，是支持同一个对象多次 add 进去的，我想这不是导致你这个问题的原因。

总之，你的这个问题不属于 **MultiType** 的范畴，或者说，不属于 **MultiType** 的问题，因此暂时关闭讨论。如有疑问或需要帮助，可以给我发邮件，基本上只要描述清楚自己的状况，我是有问必答。
