### ISSUE TITLE
ItemViewBinder用了之后 出现数组越界 但是我换成ItemViewProvider之后就没有问题

### ISSUE THREAD

**Issue by FightLi1017** [drakeet/MultiType#98]
java.lang.ArrayIndexOutOfBoundsException: length=16; index=-1
                      at java.util.ArrayList.get(ArrayList.java:315)
                      at me.drakeet.multitype.MultiTypeAdapter.getBinderByViewHolder(MultiTypeAdapter.java:217)
                      at me.drakeet.multitype.MultiTypeAdapter.onViewDetachedFromWindow(MultiTypeAdapter.java:210)
                      at android.support.v7.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:6821)
                      at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:727)
                      at android.support.v7.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
                      at android.support.v7.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:7915)
                      at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:8461)
                      at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:8447)
                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:563)
                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                      at android.view.View.layout(View.java:17088)
                      at android.view.ViewGroup.layout(ViewGroup.java:5604)
                      at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                      at android.view.View.layout(View.java:17088)
                      at android.view.ViewGroup.layout(ViewGroup.java:5604)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2022)
                      at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:2011)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1776)
                      at android.view.View.layout(View.java:17088)
                      at android.view.ViewGroup.layout(ViewGroup.java:5604)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:398)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                      at android.view.View.layout(View.java:17088)
                      at android.view.ViewGroup.layout(ViewGroup.java:5604)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2022)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1865)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1774)
                      at android.view.View.layout(View.java:17088)
                      at android.view.ViewGroup.layout(ViewGroup.java:5604)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:398)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                      at android.view.View.layout(View.java:17088)
                      at android.view.ViewGroup.layout(ViewGroup.java:5604)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2022)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1865)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1774)
                      at android.view.View.layout(View.java:17088)
                      at android.view.ViewGroup.layout(ViewGroup.java:5604)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:398)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                      at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2803)
                      at android.view.View.layout(View.java:17088)
                      at android.view.ViewGroup.layout(ViewGroup.java:5604)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2619)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2313)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1364)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6956)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:922)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:724)
                      at android.view.Choreographer.doFrame(Choreographer.java:658)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:908)
                      at android.os.Handler.handleCallback(Handler.java:819)
                      at android.os.Handler.dispatchMessage(Handler.java:104)
                      at android.os.Looper.loop(Looper.java:210)
                      at android.app.ActivityThread.main(ActivityThread.java:5932)
                  	at java.lang.reflect.Method.i

**Comment by junerver** [comment]
same issue

**Comment by drakeet** [comment]
你所谓的 "换成ItemViewProvider" 指的是 1.5.0-beta 版本的 `ItemViewProvider`？

**Comment by LcxAndroidwawa** [comment]
嗯 是的

**Comment by FightLi1017** [comment]
不是 是之前的版本

**Comment by drakeet** [comment]
看起来有可能是 1.5.0-beta 版本的 `onViewDetachedFromWindow` 方法调用的时候， holder 还没初始化，这个可能需要查看下 RecyclerView 的源码，看起来是个 BUG，十分感谢反馈！今晚将会查询详情和解决掉。

**Comment by drakeet** [comment]
@LcxAndroidwawa @junerver 能否提供能够复现的代码，最好是新起一个工程项目，然后创造复现场景。目前这个 case 我的 sample 和测试都无法复现。

**Comment by junerver** [comment]
当我在刷新一个RcyclerView，填充新的数据的时候同样出现了这样的问题；

**Comment by FightLi1017** [comment]
同上 现象一样

**Comment by drakeet** [comment]
相关代码，看起来是 `onViewDetachedFromWindow` 时，holder 的返回了 `NO_POSITION` (-1) 导致的异常，如果没办法的话，一些相关方法代理将被删除。

MultiTypeAdapter:

```
@Override 
public void onViewDetachedFromWindow(ViewHolder holder) {
    getBinderByViewHolder(holder).onViewDetachedFromWindow(holder);
}


@NonNull
private ItemViewBinder getBinderByViewHolder(@NonNull ViewHolder holder) {
    assert items != null;
    Object item = items.get(holder.getAdapterPosition()); 
    return getBinderByItem(item);
}
```

RecyclerView:

```java
int getAdapterPositionFor(ViewHolder viewHolder) {
    if (viewHolder.hasAnyOfTheFlags( ViewHolder.FLAG_INVALID |
            ViewHolder.FLAG_REMOVED | ViewHolder.FLAG_ADAPTER_POSITION_UNKNOWN)
            || !viewHolder.isBound()) {
        return RecyclerView.NO_POSITION;
    }
    return mAdapterHelper.applyPendingUpdatesToPosition(viewHolder.mPosition);
}
```

**Comment by drakeet** [comment]
@LcxAndroidwawa @junerver 对了，你们使用的 RecyclerView 是哪个版本，我使用的是 25.3.0，25.3.0 似乎是没有这个问题。

**Comment by FightLi1017** [comment]
我的也是25.3.0的版本

**Comment by drakeet** [comment]
目前我无法复现这个异常，如果可以的话，可否提供下能够复现的代码，好定位问题以及修复后验证。

**Comment by junerver** [comment]
https://github.com/junerver/TestBug/ 你好，这是可以复现这个问题的代码

**Comment by drakeet** [comment]
已经被修复了，稍后会发布 beta2 版本(#101)以及更多相关测试，十分感谢各位反馈与帮忙。

**Comment by junerver** [comment]
作者sama辛苦了！

**Comment by drakeet** [comment]
There are still bugs in 2.5.0-beta2(#102), please do not use it and wait for the fixed version.
